language: node_js
node_js:
  - "node"
before_script:
  - npm install -g parcel
script:
  - make

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: ./dist
  target-branch: gh-pages
  on:
    branch: master

addons:
  apt:
    update: true


env:
  global:
    secure: gglFmjlmoRkWaNxmIGND0yqbjHcGwZhYWMDjNGnjW3A0dhN9tUG70eE6VbFSpxDKf4two4H/WXwYoYg91tbsBQ6k4xKaw1iT6uh+cKEo7S4BCO9oICkZQAToU6orVnMcaULwzA2wjhRhY3m3WSgOdonIyB5+g2W2PAbhIUixFZNn2LOerNdRN6vMU2l0ElsEFXCG7OvSWyYaQXFgNEs3FHfXKtFxP2tl47HOHfUK+cOBeeLAJ+MBP0x+LnqNXuJE+XCNqd0D13n3I2EpIpMsqWcrIkEI9Q+jkr0TxWmlFAXq0mFa0ujnyjLS5xOk6s+3PQHVNwOtDxan9subbgtuwLnOwal1Tl6HqAvU+/WJ4fZjL4HggubL26KmYt6XLdn7A3j+PQQeO3gMdf2U8oqWoBEHGAdpiOgIywNkifjULUUI6cryY98UM2IkMhXHd1QbsQ6C02W/VcSUjpJTZo4TeFJMuqi2nVasLpkJnTUJIV58mS5DzlfbJtLYnUCpRMvfmiW7O3r9bJt3uJ94bdELlUsaXlcPtfEa9X5WYGr2cDGLo/QBugvsab5aXiYURh7SPiVC6/xQWgJiXBOsOMaXzpGn2PFrVVXOiSdRVgkPF6g/blpwW2XFErJc/rviRgb10FUQZI4RQ+iRL9pkc8NoNikwqETfHTtFgmF53c9Kvxs=
